---
spring:
  profiles:
    active: native

configserver:
  name: micro config server
  status: loaded for NATIVE from configserver/ps-micro.yml

---
spring:
  profiles:
    active: dev

configserver:
  name: micro config server
  status: loaded for DEV from configserver/ps-micro.yml